server:
  port: 10025
spring:
  application:
    name: seller_data #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.55:3306/bison?useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8
    #url: jdbc:mysql://lmdevnts0001.leaderment.com:3306/bison?useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8
    username: root
    password: root
    #password: Ldm_1910%
  jpa:
    database: MySQL
    show-sql: true
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.220:10020/eureka/
  instance:
    prefer-ip-address: true
    instance-id:  seller_data
    appname: ${spring.application.name}
    status-page-url: http://192.168.1.220:${server.port}/swagger-ui.html

mybatis:
  type-aliases-package: com.leaderment.product.pojo.mybatis_pojo
  mapper-locations: classpath:mapping/*.xml
  configuration:  #显示SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

